# Generated by Django 6.0.5 on 2026-05-26 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('failed', 'Failed Review'), ('pending_authorization', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_sms', models.TextField(help_text='Original SMS text received')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Extracted amount', max_digits=16, null=True)),
                ('currency', models.CharField(blank=True, help_text='Extracted currency (TZS, USD, etc.)', max_length=10, null=True)),
                ('sender_name', models.CharField(blank=True, help_text='Name of the person/entity sending the money', max_length=255, null=True)),
                ('from_account', models.CharField(blank=True, help_text='Source account number', max_length=100, null=True)),
                ('from_account_type', models.CharField(blank=True, help_text='Source type: BANK, MOMO, or INTL', max_length=20, null=True)),
                ('from_bank', models.CharField(blank=True, help_text='Source bank name (e.g. Mkombozi, NBC, NMB, CRDB, etc.)', max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, help_text='Name of recipient', max_length=255, null=True)),
                ('to_account', models.CharField(blank=True, help_text='Destination account number', max_length=100, null=True)),
                ('to_account_type', models.CharField(blank=True, help_text='Destination type: BANK, MOMO, or INTL', max_length=20, null=True)),
                ('to_bank', models.CharField(blank=True, help_text='Destination bank name', max_length=100, null=True)),
                ('reference', models.CharField(blank=True, help_text='Transaction reference number from SMS', max_length=255, null=True)),
                ('memo', models.TextField(blank=True, help_text='Extra description / purpose', null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date of the original transaction', null=True)),
                ('parse_confidence', models.FloatField(blank=True, help_text='Confidence score (0.0 to 1.0) of the parse', null=True)),
                ('parse_notes', models.TextField(blank=True, help_text='Notes about parsing warnings/issues', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer (if failed/discarded)', null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_notes', models.TextField(blank=True, help_text='Notes from the authorizer', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the intake source', null=True)),
                ('authorized_by', models.ForeignKey(blank=True, help_text='Authorizer who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_authorizations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Reviewer who verified this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['-created_at'],
                'permissions': [('can_review_payment', 'Can review and verify payment requests'), ('can_authorize_payment', 'Can authorize and execute payment requests')],
            },
        ),
    ]
