# Generated by Django 6.0.5 on 2026-05-20 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('recipient_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('missed', 'Missed'), ('voicemail', 'Voicemail')], default='ringing', max_length=20)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('intent_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallMenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(help_text='DTMF digit (1-9, 0, *)', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(help_text='Action to take when this option is selected', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Call Menu Option',
                'verbose_name_plural': 'Call Menu Options',
                'ordering': ['order'],
            },
        ),
    ]
