# Generated by Django 6.0.5 on 2026-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callmenuoption',
            options={'ordering': ['order'], 'verbose_name': 'IVR Menu Option', 'verbose_name_plural': 'IVR Menu Options'},
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='callmenuoption',
            name='action',
        ),
        migrations.AddField(
            model_name='callmenuoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='intent_detected',
            field=models.CharField(blank=True, help_text='Detected intent from chatbot engine', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('failed', 'Failed')], default='ringing', max_length=20),
        ),
        migrations.AlterField(
            model_name='callmenuoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callmenuoption',
            name='digit',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='callmenuoption',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
