# Generated by Django 6.0.5 on 2026-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['category', 'question'], 'verbose_name': 'Knowledge Base Entry', 'verbose_name_plural': 'Knowledge Base Entries'},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='intent_summary',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='needs_human',
        ),
        migrations.RemoveField(
            model_name='message',
            name='metadata',
        ),
        migrations.AddField(
            model_name='conversation',
            name='intent_history',
            field=models.JSONField(blank=True, default=list, help_text='List of intents detected in this conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_identifier',
            field=models.CharField(blank=True, help_text='Phone number, email, or user ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(choices=[('send_money', 'Sending Money'), ('receive_money', 'Receiving Money'), ('transfer_fees', 'Transfer Fees'), ('exchange_rates', 'Exchange Rates'), ('transfer_limits', 'Transfer Limits'), ('account_verification', 'Account Verification'), ('recipient_info', 'Recipient Information'), ('delivery_times', 'Delivery Times'), ('cancellations', 'Cancellations & Refunds'), ('security', 'Security & Fraud'), ('promotions', 'Promotions & Offers'), ('faq', 'General FAQ')], default='faq', max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for matching', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10),
        ),
    ]
