# Generated by Django 6.0.5 on 2026-05-20 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Keyword to trigger this auto-reply', max_length=100, unique=True)),
                ('reply_text', models.TextField(help_text='The auto-reply message')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Auto Reply',
                'verbose_name_plural': 'SMS Auto Replies',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=20)),
                ('intent_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_reply', models.TextField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=True, help_text='Was this handled by the robot?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
