# Generated by Django 6.0.5 on 2026-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsautoreply',
            name='keyword',
            field=models.CharField(help_text='Keyword to trigger this auto-reply', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='smsautoreply',
            name='reply_text',
            field=models.TextField(help_text='The auto-reply text to send'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='auto_reply',
            field=models.TextField(blank=True, help_text='The auto-reply sent by the chatbot', null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='intent_detected',
            field=models.CharField(blank=True, help_text='Detected intent from chatbot engine', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='Was this message handled automatically by the chatbot?'),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
